[font]
size = 16

[font.normal]
family = "FiraCode Nerd Font"

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.9

[window.padding]
x = 10
y = 3

[[keyboard.bindings]]
key = "J"
mods = "Control|Shift"
action = "ScrollLineDown"

[[keyboard.bindings]]
key = "K"
mods = "Control|Shift"
action = "ScrollLineUp"
