# Gruvbox Dark Medium Theme for Alacritty
# Source: Based on official Gruvbox palette

[colors]
# Default colors
[colors.primary]
background = '#282828'
foreground = '#ebdbb2'

# Cursor colors
[colors.cursor]
text = '#282828'
cursor = '#ebdbb2'

# Selection colors
[colors.selection]
text = '#282828'
background = '#a89984'

# Normal colors
[colors.normal]
black = '#282828'
red = '#cc241d'
green = '#98971a'
yellow = '#d79921'
blue = '#458588'
magenta = '#b16286'
cyan = '#689d6a'
white = '#a89984'

# Bright colors
[colors.bright]
black = '#928374'
red = '#fb4934'
green = '#b8bb26'
yellow = '#fabd2f'
blue = '#83a598'
magenta = '#d3869b'
cyan = '#8ec07c'
white = '#ebdbb2'
