[colors.primary]
foreground = '#ebdbb2'

[font]
size = 12

[font.normal]
family = "UbuntuMono Nerd Font"

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.94

[window.padding]
x = 10
y = 3

[terminal.shell]
program = "nu"
[general]
working_directory = "C:/Users/usr/Documents"
